import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';
import '../../../../core/theme/app_theme.dart';

class PemilikMarketplacePendapatanView extends StatelessWidget {
  const PemilikMarketplacePendapatanView({super.key});
  @override Widget build(BuildContext context) => SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(20, 16, 20, 28), children: [
    const Text('Pendapatan', style: TextStyle(fontSize: 22, fontWeight: FontWeight.w800)), const SizedBox(height: 4), const Text('Pantau performa penjualan outlet Anda.', style: TextStyle(color: AppColors.textSecondary)), const SizedBox(height: 18),
    Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: AppColors.primary, borderRadius: BorderRadius.circular(24)), child: const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('TOTAL PENDAPATAN', style: TextStyle(color: Colors.white70, fontWeight: FontWeight.bold, fontSize: 12)), SizedBox(height: 8), Text('Rp 5.420.000', style: TextStyle(color: Colors.white, fontSize: 28, fontWeight: FontWeight.w800)), SizedBox(height: 8), Text('+12,5% dibanding bulan lalu', style: TextStyle(color: Colors.white, fontWeight: FontWeight.w600))])),
    const SizedBox(height: 16), GridView.count(crossAxisCount: 2, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), mainAxisSpacing: 12, crossAxisSpacing: 12, childAspectRatio: 1.45, children: const [_Metric(title: 'Hari ini', value: 'Rp 320.000', icon: LucideIcons.calendarDays), _Metric(title: 'Minggu ini', value: 'Rp 1.850.000', icon: LucideIcons.calendarRange), _Metric(title: 'Bulan ini', value: 'Rp 5.420.000', icon: LucideIcons.chartNoAxesCombined), _Metric(title: 'Saldo tersedia', value: 'Rp 1.240.000', icon: LucideIcons.wallet)]),
    const SizedBox(height: 22), const Text('Performa 5 Hari Terakhir', style: TextStyle(fontSize: 17, fontWeight: FontWeight.w800)), const SizedBox(height: 12), Container(height: 190, padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(20), border: Border.all(color: AppColors.border)), child: const _EarningsChart()),
  ]));
}
class _Metric extends StatelessWidget { const _Metric({required this.title, required this.value, required this.icon}); final String title; final String value; final IconData icon; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(14), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Icon(icon, size: 18, color: AppColors.primary), const SizedBox(height: 8), Text(title, style: const TextStyle(fontSize: 11, color: AppColors.textSecondary)), const SizedBox(height: 2), Text(value, style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w800))])); }
class _EarningsChart extends StatelessWidget { const _EarningsChart(); @override Widget build(BuildContext context) => CustomPaint(painter: _ChartPainter(), child: const SizedBox.expand()); }
class _ChartPainter extends CustomPainter { @override void paint(Canvas canvas, Size size) { final paint = Paint()..color = AppColors.primary..style = PaintingStyle.stroke..strokeWidth = 3..strokeCap = StrokeCap.round; final path = Path()..moveTo(0, size.height * .75)..cubicTo(size.width * .12, size.height * .55, size.width * .20, size.height * .75, size.width * .31, size.height * .45)..cubicTo(size.width * .42, size.height * .15, size.width * .52, size.height * .6, size.width * .65, size.height * .4)..cubicTo(size.width * .78, size.height * .18, size.width * .88, size.height * .5, size.width, size.height * .2); canvas.drawPath(path, paint); } @override bool shouldRepaint(covariant CustomPainter oldDelegate) => false; }
