import 'package:flutter/material.dart';
import '../../../../core/theme/app_theme.dart';

class PemilikMarketplaceRiwayatView extends StatefulWidget { const PemilikMarketplaceRiwayatView({super.key}); @override State<PemilikMarketplaceRiwayatView> createState() => _PemilikMarketplaceRiwayatViewState(); }
class _PemilikMarketplaceRiwayatViewState extends State<PemilikMarketplaceRiwayatView> {
  String _filter = 'Semua';
  final _history = const [('MKT-2401', 'Deni Kurniawan', 'Nasi Timbel Komplit (2x)', 50000, 'Hari ini, 08:30', 'Selesai'), ('MKT-2399', 'Ayu Lestari', 'Es Jeruk Peras (3x)', 24000, 'Kemarin, 16:10', 'Selesai'), ('MKT-2394', 'Rizky Maulana', 'Ayam Bakar Madu', 28000, '05 Agu, 11:30', 'Dibatalkan')];
  @override Widget build(BuildContext context) { final visible = _history.where((item) => _filter == 'Semua' || item.$6 == _filter); return SafeArea(child: ListView(padding: const EdgeInsets.fromLTRB(20, 16, 20, 28), children: [const Text('Riwayat Transaksi', style: TextStyle(fontSize: 22, fontWeight: FontWeight.w800)), const SizedBox(height: 4), const Text('Temukan pesanan selesai dan dibatalkan.', style: TextStyle(color: AppColors.textSecondary)), const SizedBox(height: 16), Wrap(spacing: 8, children: ['Semua', 'Selesai', 'Dibatalkan'].map((filter) => ChoiceChip(label: Text(filter), selected: _filter == filter, selectedColor: AppColors.primary, labelStyle: TextStyle(color: _filter == filter ? Colors.white : AppColors.textPrimary), onSelected: (_) => setState(() => _filter = filter))).toList()), const SizedBox(height: 16), ...visible.map((item) => _historyCard(item))])); }
  Widget _historyCard((String, String, String, int, String, String) item) { final canceled = item.$6 == 'Dibatalkan'; return Container(margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(18), border: Border.all(color: AppColors.border)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text('#${item.$1}', style: const TextStyle(fontWeight: FontWeight.w800))), Text(item.$6, style: TextStyle(color: canceled ? Colors.red : Colors.green, fontWeight: FontWeight.bold, fontSize: 12))]), const SizedBox(height: 7), Text(item.$2, style: const TextStyle(fontWeight: FontWeight.w700)), Text(item.$3, style: const TextStyle(color: AppColors.textSecondary)), const SizedBox(height: 10), Row(children: [Text('Rp ${item.$4}', style: const TextStyle(color: AppColors.primary, fontWeight: FontWeight.w800)), const Spacer(), Text(item.$5, style: const TextStyle(color: AppColors.textMuted, fontSize: 12))]) ])); }
}
